### ISSUE TITLE
REVIEW: what's the best way to set the RowId?

### ISSUE THREAD

**Issue by xyting** [Arch/AutoHistory#1]
When the **entity** is `Modified` or `Deleted`, we can set the `RowId` to the primary key, when the **entity** is `Added`, however, we should have a way to set the `PrimaryKey` to `RowId`.

more details, see [DbContextExtensions](https://github.com/lovedotnet/AutoHistory/blob/master/src/Microsoft.EntityFrameworkCore.AutoHistory/Extensions/DbContextExtensions.cs#L47)

**Comment by xyting** [comment]
@lotosbin or anyone, have anytime to close this issue?

**Comment by alexmtnezf** [comment]
I can do it even if the primary key is a composite one.

**Comment by xyting** [comment]
@alexmtnezf Thanks!, PR welcome!

**Comment by xyting** [comment]
@alexmtnezf Are your PR ready?

**Comment by alexmtnezf** [comment]
Sorry I'm not a knower of github acronyms, what is a PR. I'm finishing my
contribution with your project but I need to submit a pull request right.
I'm a kind of new contributor in github.

**Comment by xyting** [comment]
yeah, PR = pull request

**Comment by lotosbin** [comment]
ensure entity inserted before history.

**Comment by xyting** [comment]
@lotosbin Yes, this can solve the problem, but this cause a new route trip to database. So maybe not to support the `ADD` history, only record the modify history.

**Comment by loic-montagne** [comment]
Hi there,
Finally, do you plan to support the ADD history ?
Thanks,

**Comment by xyting** [comment]
I have not good idea how to impl it in one db route trip right now.

**Comment by alexmtnezf** [comment]
What if we use a package or code from other project hosted in GitHub, if its license is MIT we can use their code right?.

**Comment by xyting** [comment]
Yep

**Comment by xyting** [comment]
@feldrim AutoHistory not want to keep a track of all DB changing. The usage is only for recording some important changes.

> That's why I believe `ADD` should not be supported and the issue should be closed.

I agree now.
