### ISSUE TITLE
AutoHistory doesn't work with UnitOfWork

### ISSUE THREAD

**Issue by chovanj** [Arch/AutoHistory#12]
Hi, AutoHistory doesn't work with UnitOfWork if atrribute is nullable.

I rewrited your UnitTest.

        public void Entity_Update_AutoHistory_Test()
        {
            var unitOfWork = new UnitOfWork<BloggingContext>(new BloggingContext());

            var blogRepository = unitOfWork.GetRepository<Blog>();
            var postRepository = unitOfWork.GetRepository<Post>();

            var blog = new Blog()
            {
                BlogId = 1,
                Url = "htttp://www.google.com/"
            };

            var post = new Post()
            {
                PostId = 1,                
                Content = "Text 1",
                Title = "Text 2"
            };

            blogRepository.Insert(blog);
            postRepository.Insert(post);

            unitOfWork.SaveChanges(true);

            post.Age = 1;           

            unitOfWork.SaveChanges(true);
        }

...
public int? Age { get; set; }
...

It throws exception

![image](https://user-images.githubusercontent.com/22910341/31360288-e98aa3ea-ad4d-11e7-8642-4e405fcebd4f.png)

**Comment by xyting** [comment]
@chovanj Thanks your report. I'll fix it this weekend.

**Comment by alexmtnezf** [comment]
This solves the issue [**see code**,](https://github.com/alexmtnezf/AutoHistory/commit/4c98de8c00941a31f868be6ea29f94c9008a4f49) just waiting for the repo owners for merging changes.

**Comment by xyting** [comment]
@alexmtnezf Thanks your PR, as this is a fix version, so I remove the breaking change, the will be release in next big version.

@chovanj Please update to [v2.0.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.AutoHistory/2.0.1)

**Comment by xyting** [comment]
Close as no more info.

**Comment by chovanj** [comment]
Great, it works! Thank you.
