### ISSUE TITLE
Changed column too short

### ISSUE THREAD

**Issue by chovanj** [Arch/AutoHistory#13]
Hello,

Is there any reason for having the **Changed** column just 2048 long?

![image](https://user-images.githubusercontent.com/22910341/31863693-6a5ccf72-b751-11e7-882f-18fea1fad05c.png)

Couldn't be replaced by **nvarchar(max)**?

**Comment by xyting** [comment]
Haven't any reason, can be replaced by nvarchar(max)

**Comment by chovanj** [comment]
It would be great, because if you have more nvarchar columns in a table and you log before and after values in JSON in the AuditHistory table then it's very easy to exceed 2048 nvarchars.

**Comment by xyting** [comment]
Yes, reasonable requirement.

**Comment by mvarblow** [comment]
This limit is a problem for me, too. I've solved the problem a bit differently, by making the maximum length an optional parameter to the EnableAutoHistory method.

**Comment by mvarblow** [comment]
What are the chances of getting a new nuget package published soon with one of these pull requests?

**Comment by xyting** [comment]
Soon, maybe this weekend.

**Comment by mvarblow** [comment]
Great!! Thanks.  Looking forward to it.

**Comment by xyting** [comment]
Had release a new fix version [v2.0.2](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.AutoHistory/2.0.2).

@mvarblow Thanks your PR

**Comment by mvarblow** [comment]
Thanks. And thanks for putting this library together and sharing it!
