### ISSUE TITLE
AutoHistory is not working with PostgreSQL

### ISSUE THREAD

**Issue by attiqeurrehman** [Arch/AutoHistory#16]
Hi,

The AutoHistory table is created in the database but there are no records. 

My config is:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // enable auto history functionality, 22023 is max limit supported by PostgreSQL
    modelBuilder.EnableAutoHistory(22023);
}
```

and during any save or update I am using the following:

```c#
await UnitOfWork.SaveChangesAsync(true);
```

### Further technical details
EF Core version: 2.0.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio Enterprise 2017 15.4.5

**Comment by xyting** [comment]
Can debugging why?

**Comment by alexmtnezf** [comment]
@attiqeurrehman just a question? Did you write this code before the saving changes: **dbContext.EnsureAutoHistory()**?

**Comment by attiqeurrehman** [comment]
@alexmtnezf I am using [UnitOfWork](https://github.com/Arch/UnitOfWork) and using the following function:

```c#
// <summary>
        /// Asynchronously saves all changes made in this unit of work to the database.
        /// </summary>
        /// <param name="ensureAutoHistory"><c>True</c> if save changes ensure auto record the change history.</param>
        /// <returns>A <see cref="Task{TResult}"/> that represents the asynchronous save operation. The task result contains the number of state entities written to database.</returns>
        public async Task<int> SaveChangesAsync(bool ensureAutoHistory = false)
        {
            if (ensureAutoHistory)
            {
                _context.EnsureAutoHistory();
            }

            return await _context.SaveChangesAsync();
        }
```

I am passing true for each Save.

```c#
await UnitOfWork.SaveChangesAsync(true);
```

**Comment by xyting** [comment]
@alexmtnezf Please install `PostgreSQL` and debugging for this issues, I'm too busy recently, thnaks

**Comment by alexmtnezf** [comment]
@attiqeurrehman I tested an ASP.NET Core project that I'm developing doing the following things:
1. Installed the Npgsql nuget package and the extension for EFCore. (OK)
2. Run migrations (OK)
3. Run the project, saved an entity (nothing happened since AutoHistory doesn't support added entities), and finally I updated the same entity and voila ( there are records in AutoHistory table).

**Comment by xyting** [comment]
@alexmtnezf Good job, thanks!

**Comment by xyting** [comment]
Close because not more info
