### ISSUE TITLE
History, Before And After Json Looks Same

### ISSUE THREAD

**Issue by SPEMoorthy** [Arch/AutoHistory#19]
Hi

I am getting Auto History Result is as follows.

{
  "before": {
    "Addr1": "string",
    "Addr2": "string",
    "CntPerson": "string",
    "CntPersonPhone": "string",
    "CreatedBy": "Easwar",
    "CreatedDate": "2018-01-27T13:50:37.2754446",
    "EMail": "string",
    "GstNumber": "string",
    "IndiaState": "string",
    "IsActive": true,
    "MfrName": "Abott International",
    "MfrShortName": "string",
    "PanNumber": "string",
    "Phone": "string",
    "PinCode": "string",
    "Place": "string",
    "TinNumber": "string",
    "TransactionTime": "0001-01-01T00:00:00",
    "UpdatedBy": "Easwar",
    "UpdatedDate": "2018-01-27T13:50:37.2754446"
  },
  "after": {
    "Addr1": "string",
    "Addr2": "string",
    "CntPerson": "string",
    "CntPersonPhone": "string",
    "CreatedBy": "Easwar",
    "CreatedDate": "2018-01-27T13:50:37.2754446",
    "EMail": "string",
    "GstNumber": "string",
    "IndiaState": "string",
    "IsActive": true,
    "MfrName": "Abott International",
    "MfrShortName": "string",
    "PanNumber": "string",
    "Phone": "string",
    "PinCode": "string",
    "Place": "string",
    "TinNumber": "string",
    "TransactionTime": "0001-01-01T00:00:00",
    "UpdatedBy": "Easwar",
    "UpdatedDate": "2018-01-27T13:50:37.2754446"
  }
}

It Seems Before and After object are Same. Any Issue?

**Comment by SPEmoorthy** [comment]
We Are Using Disconnected Entities..... That's is reason Before And After looks same.

**Comment by SPEmoorthy** [comment]
Hi All, 
Workarround Solution...

Disconnected Entities Not Having Original Values. As a workaround we need a roundtrip to db to get the original values.

 Added   


           //Get The Original Values from DB
            entry.OriginalValues.SetValues(entry.GetDatabaseValues()); 


in AutoHistory Method.


          internal static AutoHistory AutoHistory(this EntityEntry entry)
        {
            var history = new AutoHistory
            {
                TableName = entry.Metadata.Relational().TableName,
            };

            //Get The Original Values from DB
            entry.OriginalValues.SetValues(entry.GetDatabaseValues());

            // Get the mapped properties for the entity type.
            // (include shadow properties, not include navigations & references)
            var properties = entry.Properties;

            var json = new JObject();
            switch (entry.State)
            {
                case EntityState.Added:
                    foreach (var prop in properties)
                    {
                        if (prop.Metadata.IsKey() || prop.Metadata.IsForeignKey())
                        {
                            continue;
                        }
                        json[prop.Metadata.Name] = prop.CurrentValue != null
                            ? JToken.FromObject(prop.CurrentValue, _jsonerializer)
                            : JValue.CreateNull();
                    }

                    // REVIEW: what's the best way to set the RowId?
                    history.RowId = "0";
                    history.Kind = EntityState.Added;
                    history.Changed = json.ToString();
                    break;
                case EntityState.Modified:
                    var bef = new JObject();
                    var aft = new JObject();

                    foreach (var prop in properties)
                    {
                        if (prop.IsModified)
                        {
                            bef[prop.Metadata.Name] = prop.OriginalValue != null
                            ? JToken.FromObject(prop.OriginalValue, _jsonerializer)
                            : JValue.CreateNull();

                            aft[prop.Metadata.Name] = prop.CurrentValue != null
                            ? JToken.FromObject(prop.CurrentValue, _jsonerializer)
                            : JValue.CreateNull();
                        }
                    }

                    json["before"] = bef;
                    json["after"] = aft;

                    history.RowId = entry.PrimaryKey();
                    history.Kind = EntityState.Modified;
                    history.Changed = json.ToString();
                    break;
                case EntityState.Deleted:
                    foreach (var prop in properties)
                    {
                        json[prop.Metadata.Name] = prop.OriginalValue != null
                            ? JToken.FromObject(prop.OriginalValue, _jsonerializer)
                            : JValue.CreateNull();
                    }
                    history.RowId = entry.PrimaryKey();
                    history.Kind = EntityState.Deleted;
                    history.Changed = json.ToString();
                    break;
                case EntityState.Detached:
                case EntityState.Unchanged:
                default:
                    throw new NotSupportedException("AutoHistory only support Deleted and Modified entity.");
            }

            return history;
        }

Requesting Team to Review the changes and do the needfull.

**Comment by xyting** [comment]
Good, but the following code will always has more database roundtrip even if the entry have the original values:
```csharp
//Get The Original Values from DB
 switch (entry.State)
{
        case EntityState.Modified:
         case EntityState.Deleted:
        entry.OriginalValues.SetValues(entry.GetDatabaseValues());
        break;
}
```

So, we need a way to check this. Do you think so?

**Comment by SPEmoorthy** [comment]
Yes, @xyting  I agree with you. We need a way to identify the entry has original values. As of now can we introduce a flag to load the values from db or not. OR Any way in EF While attaching an entity to context... pull the original values from DB?

**Comment by xyting** [comment]
@SPEMoorthy As EFCore repo say, maybe you SHOULD set the orignal values when attaches your entity. Or this repo will provide a flag to do it.

**Comment by SPEMoorthy** [comment]
@xyting If this repo introduces a flag for loadOriginalValuesfromDb.. It Will be helpful. I tried to load originalvalues from PrepareSave method of EFCore. it failed. 

Can we Introduce a flag? If so pls guide me how to do that.

**Comment by xyting** [comment]
```csharp
internal static AutoHistory AutoHistory(this EntityEntry entry, bool loadingOrignalValuesFromDatabase = false)
```

**Comment by SPEMoorthy** [comment]
@xyting Thanks,

I hope w need to Change ..

             public static void EnsureAutoHistory(this DbContext context, bool 
                                                loadingOrignalValuesFromDatabase = false)
              {
                       // Must ToArray() here for excluding the AutoHistory model.
                              // Currently, only support Modified and Deleted entity.
                         var entries = context.ChangeTracker.Entries().Where(e => e.State == EntityState.Modified 
                        || e.State == EntityState.Deleted).ToArray();
                      foreach (var entry in entries)
                     {
                        context.Add(entry.AutoHistory(loadingOrignalValuesFromDatabase));
                         }
                     }

And Even in UOW Repository As We are consuming Autohistory from UOW Framework


        /// <summary>
        /// Saves all changes made in this context to the database.
        /// </summary>
        /// <param name="ensureAutoHistory"><c>True</c> if save changes ensure auto record the change history.</param>
        /// <param name="loadingOrignalValuesFromDatabase"></param>
        /// <returns>The number of state entries written to the database.</returns>
        public int SaveChanges(bool ensureAutoHistory = false, bool loadingOrignalValuesFromDatabase = false)
        {
            if (ensureAutoHistory)
            {
                _context.EnsureAutoHistory(loadingOrignalValuesFromDatabase);
            }

            return _context.SaveChanges();
        }

        /// <summary>
        /// Asynchronously saves all changes made in this unit of work to the database.
        /// </summary>
        /// <param name="ensureAutoHistory"><c>True</c> if save changes ensure auto record the change history.</param>
        /// <param name="loadingOrignalValuesFromDatabase"></param>
        /// <returns>A <see cref="Task{TResult}"/> that represents the asynchronous save operation. The task result contains the number of state entities written to database.</returns>
        public async Task<int> SaveChangesAsync(bool ensureAutoHistory = false, bool loadingOrignalValuesFromDatabase = false)
        {
            if (ensureAutoHistory)
            {
                _context.EnsureAutoHistory(loadingOrignalValuesFromDatabase);
            }

            return await _context.SaveChangesAsync();
        }



If the changes are fine. Requesting you to create an enhancement request for this repo and in UOW Repo.

**Comment by SPEMoorthy** [comment]
I Agree

**Comment by matsennin** [comment]
Sorry but i didn't get it...i need to get the old entity and i attached so you can Save the previous values?

**Comment by bDino** [comment]
I am aware that this is closed but I believe i am experiencing exactly this problem.  With EF Core 2.2 AutoHistory stopped working after changing all my Controller actions to async/await. Now when updating an entity it only produces "detached" histories with NULL in the "changed" column. Could someone point me in the right direction?
