### ISSUE TITLE
Question: How do I access the history entries

### ISSUE THREAD

**Issue by pwfraley** [Arch/AutoHistory#25]
Moin :)

I do have the question on how I do access the history entries?  Are there methods available on the object, like:

```
Person person = _context.person.Find(1);
person.History()
```

Or are there other ways to access the history entries for a database row?

Thanks :)

**Comment by xyting** [comment]
Currently, not have not provide ways to simplify access the history entities

**Comment by difitec-ebertp** [comment]
Hi,
is there anything new to this topic by now? Is anything planned?
Where is the point in saving a history via EF, but not being able to read it via EF?
Is there a recommended way to read the history for now?
Thanx
