### ISSUE TITLE
insertion history

### ISSUE THREAD

**Issue by farhanmughal222** [Arch/AutoHistory#26]
When are you planning to add feature of insertion history, as currently it supports only updation and deletions

**Comment by xyting** [comment]
Insertion history need one more database roundtrip, or I not found any easy way to impl it. On the other hand, the first update history had record it, do U think so?

**Comment by xyting** [comment]
Close because have not more info

**Comment by NormanGiHu** [comment]
I think, when not having a timestamp column in a given table there is no way to get the time, when the record was first inserted, if the "add" action is not in AutoHistory.
