### ISSUE TITLE
Publish new Nuget package

### ISSUE THREAD

**Issue by ericgreenmix** [Arch/AutoHistory#41]
Could you get a new nuget package published with the support for EF Core 3 that got merged in?

**Comment by xyting** [comment]
Maybe this weekend, I need some time to learn what's new in EF Core 3.0. Or somebody please give a PR

**Comment by ericgreenmix** [comment]
You already merged my PR for EF core 3 support a couple weeks ago. What else did you want a PR for?

**Comment by xyting** [comment]
OK, published a new nuget package now

**Comment by xyting** [comment]
see [v3.0.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.AutoHistory/3.0.1)

**Comment by ericgreenmix** [comment]
Awesome! Thanks!
