### ISSUE TITLE
did not work win .net standard 2.0

### ISSUE THREAD

**Issue by MohMehrnia** [Arch/AutoHistory#46]
HI, the latest update did not work with dotnet standard 2.0 but entity framework 3.1 work with .net standard 2.0

**Comment by xyting** [comment]
I'll fix some issues and select standard 2.0

**Comment by xyting** [comment]
see [v3.1.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.AutoHistory/3.1.1)
