### ISSUE TITLE
How to reread AutoHistory table from context

### ISSUE THREAD

**Issue by SleepyDeb** [Arch/AutoHistory#6]
AutoHistory model is market like internal,

I have no way to re read auto history records

**Comment by xyting** [comment]
@SleepyDeb Next release, I'll change to public. Right now, you can use `FromSql` method.

**Comment by SleepyDeb** [comment]
but if i use InMemoryDatabase there is no way, i embedded your source directly in my codebase, and there is another bug related to enum values.

**Comment by xyting** [comment]
Please give the more info about the enum bug.

**Comment by SleepyDeb** [comment]
Ok, i had not time to give you informations.

I make a mistake, is not a bug on enums,

The bug is when you use Bind() (Eg: from REST Api parameters) there is no way for your library to get old values from the entity instance.

PropertyEntry contains wrong value in OriginalValue.

Thx

**Comment by xyting** [comment]
see [v2.0.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.AutoHistory/2.0.0)
