### ISSUE TITLE
Design: use entity name rather than TableName?

### ISSUE THREAD

**Issue by xyting** [Arch/AutoHistory#8]

**Comment by alexmtnezf** [comment]
I can do it and implement other features if you want to.
1. Adding the not logged required properties into the EnsureHistory, for example, if we don't want to log the created date in the history when you are updating a record.
2. Passing the email or name of who is doing the change.
3. Adding support for new or added entities.

**Comment by xyting** [comment]
@alexmtnezf Very good, give me help. PR welcome!

**Comment by xyting** [comment]
@alexmtnezf Are your PR ready?
